
let salesData = [ 
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "INVITATION_SENT",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": "182 CNCNCN2022",
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "INVITATION_DELIVERED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "INVITATION_NOT_RECEIVED",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "SIGNED_UP",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "FINISHED",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "UNKOWN",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
    "enrolmentStatus": "SAGHASHASHSAH",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": "2021-12-12",
    "commissionNumber": "182 WVWCAT2021",
    "customerId": 61,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer1",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "John Doe",
    "invitationDate": "2023-07-05T13:01:30",
    "modelName": "ID.3 Pure 093/45 E1R",
    "orderProgress": "SHIPPED_FROM_FACTORY",
    "vin": "BVWTDME1ZLP402201",
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 46,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer2",
    "dealershipId": "DEU06780V",
    "enrolmentStatus": "TERMS_AND_CONDITIONS_ACCEPTED",
    "fullName": "JC Test PN",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 48,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Mariah Carey",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 4,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer4",
    "dealershipId": "DEU06780V",
    "fullName": "Number 4",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 5,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer5",
    "dealershipId": "DEU06780V",
    "fullName": "Five Guys",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 6,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer6",
    "dealershipId": "DEU06780V",
    "fullName": "Six,...",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 7,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer7",
    "dealershipId": "DEU06780V",
    "fullName": "O O 7",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 8,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer8",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 8",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 9,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer9",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 9",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 10,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer10",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 10",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 11,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 11",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 12,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 12",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 13,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 13",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
},
{
    "arrivalDate": null,
    "commissionNumber": null,
    "customerId": 14,
    "dealerId": "dpm66e0",
    "dealerName": "NextGen Dealer3",
    "dealershipId": "DEU06780V",
    "fullName": "Customer 14",
    "invitationDate": "2023-06-28T17:06:30",
    "modelName": null,
    "orderProgress": null,
    "vin": null,
}]

module.exports = salesData;
